# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Programação\Relay 2Ch\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 358)
        MainWindow.setMinimumSize(QtCore.QSize(680, 358))
        MainWindow.setMaximumSize(QtCore.QSize(680, 358))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 661, 291))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.label.setObjectName("label")
        self.lineEdit_ip = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_ip.setGeometry(QtCore.QRect(90, 20, 181, 20))
        self.lineEdit_ip.setInputMask("")
        self.lineEdit_ip.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2_senha = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2_senha.setGeometry(QtCore.QRect(90, 50, 113, 20))
        self.lineEdit_2_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2_senha.setObjectName("lineEdit_2_senha")
        self.pushButton_conectar = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_conectar.setGeometry(QtCore.QRect(290, 20, 75, 23))
        self.pushButton_conectar.setObjectName("pushButton_conectar")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 211, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_2_ligar_r01 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2_ligar_r01.setGeometry(QtCore.QRect(10, 110, 75, 23))
        self.pushButton_2_ligar_r01.setObjectName("pushButton_2_ligar_r01")
        self.pushButton_3_desligar_01 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3_desligar_01.setGeometry(QtCore.QRect(120, 110, 75, 23))
        self.pushButton_3_desligar_01.setObjectName("pushButton_3_desligar_01")
        self.label_3_status_r01 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3_status_r01.setGeometry(QtCore.QRect(10, 80, 181, 16))
        self.label_3_status_r01.setText("")
        self.label_3_status_r01.setObjectName("label_3_status_r01")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(230, 110, 201, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_4_ligar_r02 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4_ligar_r02.setGeometry(QtCore.QRect(20, 110, 75, 23))
        self.pushButton_4_ligar_r02.setObjectName("pushButton_4_ligar_r02")
        self.pushButton_5_desligar_r02 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5_desligar_r02.setGeometry(QtCore.QRect(120, 110, 75, 23))
        self.pushButton_5_desligar_r02.setObjectName("pushButton_5_desligar_r02")
        self.label_4_status_r02 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4_status_r02.setGeometry(QtCore.QRect(20, 80, 171, 16))
        self.label_4_status_r02.setText("")
        self.label_4_status_r02.setObjectName("label_4_status_r02")
        self.label_3_status_conexao = QtWidgets.QLabel(self.groupBox)
        self.label_3_status_conexao.setGeometry(QtCore.QRect(290, 50, 111, 16))
        self.label_3_status_conexao.setText("")
        self.label_3_status_conexao.setObjectName("label_3_status_conexao")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(440, 30, 211, 251))
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(440, 10, 111, 16))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Controle "))
        self.groupBox.setTitle(_translate("MainWindow", "Placa 01 "))
        self.label.setText(_translate("MainWindow", "IP:"))
        self.label_2.setText(_translate("MainWindow", "Senha:"))
        self.pushButton_conectar.setText(_translate("MainWindow", "Conectar"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Relé 01"))
        self.pushButton_2_ligar_r01.setText(_translate("MainWindow", "Ligar"))
        self.pushButton_3_desligar_01.setText(_translate("MainWindow", "Desligar"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Relé 02"))
        self.pushButton_4_ligar_r02.setText(_translate("MainWindow", "Ligar"))
        self.pushButton_5_desligar_r02.setText(_translate("MainWindow", "Desligar"))
        self.label_3.setText(_translate("MainWindow", "Histório de Eventos:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
